name: "Install SSH Key"
description: "Install SSH key in ~/.ssh"
author: "jzizka"
inputs:
  private_key:
    description: "SSH private key"
    required: true
  known_hosts:
    description: "known keys of SSH servers"
    required: true
runs:
  using: "composite"
  steps:
    - name: 'Pre-action checks'
      shell: bash
      run: |
        # Validate inputs
        if [ -z "${{ inputs.private_key }}" ]; then
          echo "private_key is not defined!Please define your private_key"
          exit 1
        elif [ -z "${{ inputs.known_hosts }}" ]; then
          echo "known_hosts is not defined!Please define your known_hosts"
          exit 1
        fi
    - name: 'Setup SSH Key'
      shell: bash
      run: |
        umask 077 && mkdir -p ~/.ssh
        umask 133 && echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK
        ssh-add - <<< "$SSH_PRIVATE_KEY"
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
      env:
        SSH_PRIVATE_KEY: "${{ inputs.private_key }}"
        SSH_KNOWN_HOSTS: "${{ inputs.known_hosts }}"
        SSH_AUTH_SOCK: "/tmp/ssh_agent.sock"
